
TRANSACTION_COLUMNS = ('DATE','ITEM','PROJECT','ADD','PRICE','USE','NOTE')
#TRANSACTION_COLUMNS = ('DATE','ITEM','PROJECT','ADD','PRICE','USE','NOTE')
BALANCE_COLUMNS = ('ITEM','BALANCE')

TRANSACTION_NODE_NAME = 'Transaction/'
BALANCE_NODE_NAME = 'Balance/'
TRANSACTION_SIZE_NODE_NAME = 'Transaction/size'
BALANCE_SIZE_NODE_NAME = 'Balance/size'